shell = "bash -c '{}'"

[[items]]
file = "~/.config/foot/foot.ini"
template = "foot"

[[items]]
file = "~/.config/kak/kakrc"
template = "kakoune"

[[items]]
file = "~/.config/tofi/config"
template = "tofi"
